./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_A_EH_barrel.root" "Graph" "a for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_B_EH_barrel.root" "Graph" "b for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_C_H_barrel.root" "Graph" "c for H-hadrons" 1 "Barrel Energy Calibration 2025" "E_{true} [GeV]" "Coefficients" "coefficients_Barrel_energy_calibration" -4 2.2 ""
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_A_EH_endcap.root" "Graph" "a for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_B_EH_endcap.root" "Graph" "b for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_C_H_endcap.root" "Graph" "c for H-hadrons" 1 "Endcap Energy Calibration 2025" "E_{true} [GeV]" "Coefficients" "coefficients_Endcap_energy_calibration" -3 3 ""
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Alpha_EH_barrel.root" "Graph" "#alpha for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Alpha_H_barrel.root" "Graph" "#alpha for H-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Beta_EH_barrel.root" "Graph" "#beta for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Beta_H_barrel.root" "Graph" "#beta for H-hadrons" 1 "Barrel Pseudorapidity Calibration 2025" "E_{true} [GeV]" "Coefficients" "coefficients_Barrel_eta_calibration" -0.5 0.2 ""
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Alpha_EH_endcap.root" "Graph" "#alpha for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Alpha_H_endcap.root" "Graph" "#alpha for H-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Beta_EH_endcap.root" "Graph" "#beta for EH-hadrons" "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_Beta_H_endcap.root" "Graph" "#beta for H-hadrons" 1 "Endcap Pseudorapidity Calibration 2025" "E_{true} [GeV]" "Coefficients" "coefficients_Endcap_eta_calibration" -0.5 0.3 ""



./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_2to5_GeV" "E_{true} [GeV]" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_2to5_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_5to10_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_5to10_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_10to20_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_10to20_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_20to40_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_20to40_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_40to60_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_40to60_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_60to100_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_60to100_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_100to200_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_100to200_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 withPU" 0 "EtaCorrEtaDependence_200to500_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_200to500_GeV" -1 1 "etadependence"


./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_2to5_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_2to5_GeV" "E_{true} [GeV]" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_2to5_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_5to10_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_5to10_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_5to10_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_10to20_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_10to20_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_10to20_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_20to40_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_20to40_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_20to40_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_40to60_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_40to60_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_40to60_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_60to100_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_60to100_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_60to100_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_100to200_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_100to200_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_100to200_GeV" -1 1 "etadependence"
./betterPlotter "ResponsePlots_ETrue25_v2_Bfix/rootFiles/resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 NoPU" "ResponsePlots_ETrue25_withPU/rootFiles/resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 withPU" "resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 withPU rc sup" "ResponsePlots_ETrue25_v1Old/rootFiles/resp_EtaCorrEtaDependence_200to500_GeV.root" "Graph" "2025 NoPUv1"  0 "EtaCorrEtaDependence_200to500_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_EtaCorrEtaDependence_200to500_GeV" -1 1 "etadependence"


./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_2to5_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_2to5_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_2to5_GeV" "E_{true} [GeV]" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_2to5_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_5to10_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_5to10_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_5to10_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_5to10_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_10to20_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_10to20_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_10to20_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_10to20_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_20to40_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_20to40_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_20to40_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_20to40_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_40to60_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_40to60_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_40to60_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_40to60_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_60to100_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_60to100_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_60to100_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_60to100_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_100to200_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_100to200_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_100to200_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_100to200_GeV" -1 1 "etadependence"
./betterPlotter "NoPU_onlyChargedHadrons/resp_RawEtaDependence_200to500_GeV.root" "Graph" "2025 NoPU c!=0" "WithPU_onlyChargedHadrons/resp_RawEtaDependence_200to500_GeV.root" "Graph" "2025 withPU c!=0" 0 "RawEtaDependence_200to500_GeV" "|#eta|" "(E_{cor}-E_{true})/E_{true}" "comparison_RawEtaDependence_200to500_GeV" -1 1 "etadependence"
